version: 2
updates:
  - directory: /
    package-ecosystem: npm
    schedule:
      interval: daily
    pull-request-branch-name:
      separator: '-'
    target-branch: main
    ignore:
      - dependency-name: '*'
        update-types: ['version-update:semver-major']
      - dependency-name: '@types/node'
    commit-message:
      prefix: chore(deps)
