name: Add labels to PR

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize

jobs:
  add-labels:
    name: Add labels
    runs-on: ubuntu-latest
    steps:
      - uses: srvaroa/labeler@v0.9
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
