name: Check pull request title

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize

jobs:
  check-pull-request-title:
    name: Check pull request title
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
