name: Define labels

on:
  push:
    branches:
      - main
    paths:
      - .github/labels.yml

jobs:
  define-labels:
    name: Define labels
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: micnncim/action-label-syncer@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          manifest: .github/labels.yml
