name: flow-define-labels

on:
  push:
    branches:
      - main
    paths:
      - .github/labels.yml

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  update-labels:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: micnncim/action-label-syncer@v1
        with:
          manifest: .github/labels.yml
