name: flow-push

on: push

jobs:
  install:
    uses: ./.github/workflows/job-install.yml
    secrets: inherit
  format:
    needs: [install]
    uses: ./.github/workflows/job-format.yml
    secrets: inherit
  lint:
    needs: [install]
    uses: ./.github/workflows/job-lint.yml
    secrets: inherit
  test:
    needs: [install]
    uses: ./.github/workflows/job-test.yml
    secrets: inherit
  build:
    needs: [install]
    uses: ./.github/workflows/job-build.yml
    secrets: inherit
  analyze:
    uses: ./.github/workflows/job-analyze.yml
    secrets: inherit
  security:
    uses: ./.github/workflows/job-security.yml
    secrets: inherit
  release:
    if: ${{ github.ref == 'refs/heads/main' }}
    needs: [format, lint, test, build, analyze, security]
    uses: ./.github/workflows/job-release.yml
    secrets: inherit
  docs:
    needs: [release]
    uses: ./.github/workflows/job-docs.yml
    secrets: inherit
