name: flow-pr

on: pull_request

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  check-title:
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v4
  add-labels:
    runs-on: ubuntu-latest
    steps:
      - uses: srvaroa/labeler@v0.9
