name: flow-dependabot

on: pull_request_target

permissions:
  pull-requests: write
  contents: write

env:
  PR_URL: ${{ github.event.pull_request.html_url }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  merge:
    if: ${{ github.actor == 'dependabot[bot]' }}
    runs-on: ubuntu-latest
    steps:
      - run: |
          gh pr merge --auto --squash "$PR_URL"
          gh pr review --approve "$PR_URL"
