name: Merge dependabot PR

on: pull_request_target

permissions:
  pull-requests: write
  contents: write

env:
  PR_URL: ${{ github.event.pull_request.html_url }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  merge-dependabot:
    name: Accept PR
    runs-on: ubuntu-latest
    if: ${{ github.event.pull_request.user.login == 'dependabot[bot]' }}
    steps:
      - name: Enable auto-merge on PR
        run: gh pr merge --auto --squash "$PR_URL"
      - name: Approve PR
        run: gh pr review --approve "$PR_URL"
