name: Release version

on:
  release:
    types:
      - released

concurrency:
  group: ${{ github.event.release.tag_name }}
  cancel-in-progress: true

jobs:
  publish:
    name: Publish package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: 'https://registry.npmjs.org'
      - run: |
          npm ci
          npm test
          npm run build
          npm version from-git --allow-same-version --no-git-tag-version
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
